import type { components } from "./schema";

export type UserResponse = components["schemas"]["UserResponse"];
export type UserListResponse = components["schemas"]["UserListResponse"];
export type UserCreate = components["schemas"]["UserCreate"];
export type UserUpdate = components["schemas"]["UserUpdate"];
export type UserStatus = components["schemas"]["UserStatus"];
export type RoleResponse = components["schemas"]["RoleResponse"];
export type RoleCreate = components["schemas"]["RoleCreate"];
export type RoleRename = components["schemas"]["RoleRename"];
export type ModuleResponse = components["schemas"]["ModuleResponse"];
export type ModuleGroup = components["schemas"]["ModuleGroup"];
export type ProjectResponse = components["schemas"]["ProjectResponse"];
export type ProjectAccessInput = components["schemas"]["ProjectAccessInput"];
export type ProjectAccessResponse = components["schemas"]["ProjectAccessResponse"];
export type PermissionCell = components["schemas"]["PermissionCell"];
export type PermissionUpdate = components["schemas"]["PermissionUpdate"];
export type PasswordReset = components["schemas"]["PasswordReset"];
export type AccessLevel = components["schemas"]["AccessLevel"];
export type Scope = components["schemas"]["Scope"];
export type CompanyRead = components["schemas"]["CompanyRead"];
export type CompanyUpdate = components["schemas"]["CompanyUpdate"];
export type PreferencesRead = components["schemas"]["PreferencesRead"];
export type PreferencesUpdate = components["schemas"]["PreferencesUpdate"];
export type NotificationPrefItem = components["schemas"]["NotificationPrefItem"];
export type NotificationPrefsUpdate = components["schemas"]["NotificationPrefsUpdate"];
