/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit Log Endpoint
         * @description Filtrelenebilir/sayfalanabilir denetim gunlugu listesi (`occurred_at DESC`).
         */
        get: operations["list_audit_log_endpoint_audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-log/export.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Audit Log Endpoint
         * @description Filtrelenmis denetim gunlugunu Excel dosyasi olarak doner.
         *
         *     Liste ucuyle AYNI filtreler gecerlidir; `limit`/`offset` YOKTUR — eslesen tum
         *     kayitlar yazilir (sessiz kirpma yapilmaz, bkz. plan Task 5 sinir notu).
         */
        get: operations["export_audit_log_endpoint_audit_log_export_xlsx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description token_version'ı artırır — o ana dek basılmış tüm token'lar (access + refresh) geçersiz
         *     olur (gerçek sunucu-taraflı çıkış). BFF ayrıca httpOnly cookie'yi siler.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company Endpoint */
        get: operations["get_company_endpoint_company_get"];
        /** Update Company Endpoint */
        put: operations["update_company_endpoint_company_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/company/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Logo Endpoint */
        get: operations["get_logo_endpoint_company_logo_get"];
        put?: never;
        /** Upload Logo Endpoint */
        post: operations["upload_logo_endpoint_company_logo_post"];
        /** Delete Logo Endpoint */
        delete: operations["delete_logo_endpoint_company_logo_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Summary Endpoint */
        get: operations["get_dashboard_summary_endpoint_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects Endpoint */
        get: operations["list_projects_endpoint_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Endpoint */
        get: operations["get_project_endpoint_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roles Endpoint */
        get: operations["list_roles_endpoint_roles_get"];
        put?: never;
        /** Create Role Endpoint */
        post: operations["create_role_endpoint_roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Modules Endpoint */
        get: operations["list_modules_endpoint_modules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{role_id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Role Permissions Endpoint */
        get: operations["get_role_permissions_endpoint_roles__role_id__permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Role Endpoint */
        delete: operations["delete_role_endpoint_roles__role_id__delete"];
        options?: never;
        head?: never;
        /** Rename Role Endpoint */
        patch: operations["rename_role_endpoint_roles__role_id__patch"];
        trace?: never;
    };
    "/roles/{role_id}/permissions/{module_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Permission Endpoint */
        put: operations["update_permission_endpoint_roles__role_id__permissions__module_key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences Endpoint */
        get: operations["get_preferences_endpoint_settings_preferences_get"];
        /** Update Preferences Endpoint */
        put: operations["update_preferences_endpoint_settings_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notifications Endpoint */
        get: operations["get_notifications_endpoint_settings_notifications_get"];
        /** Update Notifications Endpoint */
        put: operations["update_notifications_endpoint_settings_notifications_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users Endpoint */
        get: operations["list_users_endpoint_users_get"];
        put?: never;
        /** Create User Endpoint */
        post: operations["create_user_endpoint_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Endpoint */
        get: operations["get_user_endpoint_users__user_id__get"];
        put?: never;
        post?: never;
        /** Delete User Endpoint */
        delete: operations["delete_user_endpoint_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User Endpoint */
        patch: operations["update_user_endpoint_users__user_id__patch"];
        trace?: never;
    };
    "/users/{user_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reset Password Endpoint */
        patch: operations["reset_password_endpoint_users__user_id__password_patch"];
        trace?: never;
    };
    "/users/{user_id}/project-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Access Endpoint */
        get: operations["get_project_access_endpoint_users__user_id__project_access_get"];
        /** Set Project Access Endpoint */
        put: operations["set_project_access_endpoint_users__user_id__project_access_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessLevel
         * @description Erişim seviyesi. Sıralıdır: none < view < draft < request < approve < full < admin.
         *
         *     full silmeyi KAPSAMAZ — silme yalnızca admin seviyesindedir (spec §5.0).
         * @enum {string}
         */
        AccessLevel: "none" | "view" | "draft" | "request" | "approve" | "full" | "admin";
        /**
         * AuditAction
         * @description Denetim gunlugunde kaydedilen islem turleri.
         *
         *     `approve` ve `backup` degerleri simdiden tanimlidir; uretici uclari sonraki
         *     fazlarda (hakedis onayi, yedekleme) eklenecek.
         *
         *     Proje geneli deseni (`str, enum.Enum`) korunur; StrEnum'a gecis `__str__`
         *     davranisini degistirir (bkz. pyproject.toml UP042 notu).
         * @enum {string}
         */
        AuditAction: "login" | "create" | "update" | "delete" | "approve" | "backup";
        /**
         * AuditActorRead
         * @description Denetim satirini yapan kullanici.
         *
         *     `role_name` ZORUNLUDUR: ekranin kullanici hucresi ad + rol adini birlikte gosterir.
         */
        AuditActorRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** Role Name */
            role_name: string;
        };
        /** AuditItem */
        AuditItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            action: components["schemas"]["AuditAction"];
            /** Detail */
            detail: string;
            /** Ip Address */
            ip_address?: string | null;
            actor?: components["schemas"]["AuditActorRead"] | null;
        };
        /** AuditListResponse */
        AuditListResponse: {
            /** Items */
            items: components["schemas"]["AuditItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Body_upload_logo_endpoint_company_logo_post */
        Body_upload_logo_endpoint_company_logo_post: {
            /** File */
            file: string;
        };
        /**
         * CompanyRead
         * @description Sirket okuma modeli. Logo bytea'si ASLA burada donmez; yalnizca has_logo + logo_url.
         */
        CompanyRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
            /** Tax Number */
            tax_number: string | null;
            /** Tax Office */
            tax_office: string | null;
            /** Trade Registry No */
            trade_registry_no: string | null;
            /** Kep Address */
            kep_address: string | null;
            /** Phone */
            phone: string | null;
            /** Email */
            email: string | null;
            /** Website */
            website: string | null;
            /** Address */
            address: string | null;
            /** Brand Color */
            brand_color: string;
            /** Gib Integration Code */
            gib_integration_code: string | null;
            /** Earsiv Portal */
            earsiv_portal: string | null;
            /** Default Vat Rate */
            default_vat_rate: string;
            /** Auto Einvoice */
            auto_einvoice: boolean;
            /** Has Logo */
            has_logo: boolean;
            /** Logo Url */
            logo_url: string;
        };
        /**
         * CompanyUpdate
         * @description Kismi guncelleme — tum alanlar opsiyonel. Gonderilmeyen alan degismez.
         */
        CompanyUpdate: {
            /** Name */
            name?: string | null;
            /** Tax Number */
            tax_number?: string | null;
            /** Tax Office */
            tax_office?: string | null;
            /** Trade Registry No */
            trade_registry_no?: string | null;
            /** Kep Address */
            kep_address?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Website */
            website?: string | null;
            /** Address */
            address?: string | null;
            /** Brand Color */
            brand_color?: string | null;
            /** Gib Integration Code */
            gib_integration_code?: string | null;
            /** Earsiv Portal */
            earsiv_portal?: string | null;
            /** Default Vat Rate */
            default_vat_rate?: number | string | null;
            /** Auto Einvoice */
            auto_einvoice?: boolean | null;
        };
        /** DashboardProjectCard */
        DashboardProjectCard: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            status: components["schemas"]["ProjectStatus"];
            /** Budget */
            budget: string;
            /** Progress Pct */
            progress_pct: string;
        };
        /** DashboardSummaryResponse */
        DashboardSummaryResponse: {
            /** Role Name */
            role_name: string;
            /** Active Project Count */
            active_project_count: number;
            /** Projects */
            projects: components["schemas"]["DashboardProjectCard"][];
            portfolio: components["schemas"]["MetricPlaceholder"];
            receivables: components["schemas"]["MetricPlaceholder"];
            average_margin: components["schemas"]["MetricPlaceholder"];
            pending_approvals: components["schemas"]["PendingApprovalsPlaceholder"];
            risks: components["schemas"]["ListPlaceholder"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ListPlaceholder
         * @description Liste tipli kart (risk uyarilari).
         */
        ListPlaceholder: {
            /**
             * Available
             * @default false
             */
            available: boolean;
            /** Items */
            items?: string[];
            /** Pending Module */
            pending_module: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Title */
            title: string;
            /** Role Key */
            role_key: string;
            status: components["schemas"]["UserStatus"];
        };
        /**
         * MetricPlaceholder
         * @description Tek degerli KPI karti. v1'de veri kaynagi olmayan kartlar icin.
         *
         *     available alani bilincli olarak vardir: frontend sabite degil veriye dallanir,
         *     ilgili alt-proje geldiginde backend true dondurmeye baslar (spec §2.3).
         */
        MetricPlaceholder: {
            /**
             * Available
             * @default false
             */
            available: boolean;
            /** Value */
            value?: string | null;
            /** Pending Module */
            pending_module: string;
        };
        /**
         * ModuleGroup
         * @enum {string}
         */
        ModuleGroup: "GENEL" | "SAHA" | "STOK_SATINALMA" | "MALI" | "SISTEM";
        /** ModuleResponse */
        ModuleResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Name */
            name: string;
            group: components["schemas"]["ModuleGroup"];
            /** Sort Order */
            sort_order: number;
        };
        /** NotificationPrefItem */
        NotificationPrefItem: {
            /** Event Key */
            event_key: string;
            /** Label */
            label: string;
            /** Email */
            email: boolean;
            /** In App */
            in_app: boolean;
            /** Sms */
            sms: boolean;
        };
        /** NotificationPrefUpdateItem */
        NotificationPrefUpdateItem: {
            /** Event Key */
            event_key: string;
            /** Email */
            email: boolean;
            /** In App */
            in_app: boolean;
            /** Sms */
            sms: boolean;
        };
        /** NotificationPrefsUpdate */
        NotificationPrefsUpdate: {
            /** Items */
            items: components["schemas"]["NotificationPrefUpdateItem"][];
        };
        /** PasswordReset */
        PasswordReset: {
            /** New Password */
            new_password: string;
        };
        /**
         * PendingApprovalsPlaceholder
         * @description Onay bekleyenler karti — rozet sayaci tasir.
         */
        PendingApprovalsPlaceholder: {
            /**
             * Available
             * @default false
             */
            available: boolean;
            /** Items */
            items?: string[];
            /** Pending Module */
            pending_module: string;
            /**
             * Count
             * @default 0
             */
            count: number;
        };
        /** PermissionCell */
        PermissionCell: {
            /** Module Key */
            module_key: string;
            access_level: components["schemas"]["AccessLevel"];
            scope: components["schemas"]["Scope"];
        };
        /** PermissionUpdate */
        PermissionUpdate: {
            access_level: components["schemas"]["AccessLevel"];
            scope: components["schemas"]["Scope"];
        };
        /** PreferencesRead */
        PreferencesRead: {
            locale: components["schemas"]["UILocale"];
            currency: components["schemas"]["UICurrency"];
            /** Date Format */
            date_format: string;
            density: components["schemas"]["UIDensity"];
            theme: components["schemas"]["UITheme"];
            /** Accent Color */
            accent_color: string;
        };
        /** PreferencesUpdate */
        PreferencesUpdate: {
            locale?: components["schemas"]["UILocale"] | null;
            currency?: components["schemas"]["UICurrency"] | null;
            /** Date Format */
            date_format?: string | null;
            density?: components["schemas"]["UIDensity"] | null;
            theme?: components["schemas"]["UITheme"] | null;
            /** Accent Color */
            accent_color?: string | null;
        };
        /** ProjectAccessInput */
        ProjectAccessInput: {
            /**
             * All Projects
             * @default false
             */
            all_projects: boolean;
            /** Project Ids */
            project_ids?: string[];
        };
        /** ProjectAccessResponse */
        ProjectAccessResponse: {
            /** All Projects */
            all_projects: boolean;
            /** Project Ids */
            project_ids: string[];
        };
        /** ProjectResponse */
        ProjectResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            status: components["schemas"]["ProjectStatus"];
            /** Budget */
            budget: string;
            /** Progress Pct */
            progress_pct: string;
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "active" | "on_hold" | "completed";
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RoleCreate */
        RoleCreate: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /**
             * Emoji
             * @default
             */
            emoji: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** RoleRename */
        RoleRename: {
            /** Name */
            name: string;
            /**
             * Emoji
             * @default
             */
            emoji: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** RoleResponse */
        RoleResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Emoji */
            emoji: string;
            /** Description */
            description: string;
            /** Is System */
            is_system: boolean;
        };
        /**
         * Scope
         * @description Veri kapsamı — aktörün modül içinde hangi kayıtları görebildiği.
         * @enum {string}
         */
        Scope: "all" | "own" | "project" | "finance" | "stock" | "limited";
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UICurrency
         * @enum {string}
         */
        UICurrency: "TRY" | "USD" | "EUR";
        /**
         * UIDensity
         * @enum {string}
         */
        UIDensity: "comfortable" | "normal" | "compact";
        /**
         * UILocale
         * @enum {string}
         */
        UILocale: "tr" | "en";
        /**
         * UITheme
         * @enum {string}
         */
        UITheme: "light" | "dark" | "system";
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Role Id
             * Format: uuid
             */
            role_id: string;
            /** @default active */
            status: components["schemas"]["UserStatus"];
        };
        /** UserListResponse */
        UserListResponse: {
            /** Items */
            items: components["schemas"]["UserResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Title */
            title: string;
            /**
             * Role Id
             * Format: uuid
             */
            role_id: string;
            status: components["schemas"]["UserStatus"];
            /** Last Login At */
            last_login_at?: string | null;
        };
        /**
         * UserStatus
         * @enum {string}
         */
        UserStatus: "active" | "on_leave" | "passive";
        /** UserUpdate */
        UserUpdate: {
            /** Full Name */
            full_name?: string | null;
            /** Title */
            title?: string | null;
            /** Role Id */
            role_id?: string | null;
            status?: components["schemas"]["UserStatus"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_audit_log_endpoint_audit_log_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                actor_user_id?: string | null;
                action?: components["schemas"]["AuditAction"] | null;
                /** @description YYYY-MM-DD — o gunun 00:00'indan itibaren (Europe/Istanbul, dahil) */
                date_from?: string | null;
                /** @description YYYY-MM-DD — o gunun sonuna kadar (Europe/Istanbul, dahil) */
                date_to?: string | null;
                /** @description Detay metni veya aktor adinda kismi arama */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditListResponse"];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_audit_log_endpoint_audit_log_export_xlsx_get: {
        parameters: {
            query?: {
                actor_user_id?: string | null;
                action?: components["schemas"]["AuditAction"] | null;
                /** @description YYYY-MM-DD — o gunun 00:00'indan itibaren (Europe/Istanbul, dahil) */
                date_from?: string | null;
                /** @description YYYY-MM-DD — o gunun sonuna kadar (Europe/Istanbul, dahil) */
                date_to?: string | null;
                /** @description Detay metni veya aktor adinda kismi arama */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Excel dosyasi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": unknown;
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    get_company_endpoint_company_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyRead"];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_company_endpoint_company_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyRead"];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_logo_endpoint_company_logo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upload_logo_endpoint_company_logo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_logo_endpoint_company_logo_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyRead"];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Logo boyutu cok buyuk */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Gecersiz logo bicimi veya icerigi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_logo_endpoint_company_logo_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_dashboard_summary_endpoint_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummaryResponse"];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_projects_endpoint_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"][];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_project_endpoint_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_endpoint_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponse"][];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_role_endpoint_roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponse"];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_modules_endpoint_modules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleResponse"][];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_role_permissions_endpoint_roles__role_id__permissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionCell"][];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_role_endpoint_roles__role_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_role_endpoint_roles__role_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleRename"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponse"];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_permission_endpoint_roles__role_id__permissions__module_key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
                module_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermissionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionCell"];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences_endpoint_settings_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesRead"];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_preferences_endpoint_settings_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesRead"];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_notifications_endpoint_settings_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPrefItem"][];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_notifications_endpoint_settings_notifications_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationPrefsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPrefItem"][];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_endpoint_users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_endpoint_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_endpoint_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_endpoint_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_endpoint_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_endpoint_users__user_id__password_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordReset"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_access_endpoint_users__user_id__project_access_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectAccessResponse"];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_project_access_endpoint_users__user_id__project_access_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectAccessInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectAccessResponse"];
                };
            };
            /** @description Yetkisiz işlem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
