import type { EvQurrReport } from "@/lib/api/models";

/**
 * PLN-F3.5 · `WeeklyQurrScreen` fikstürü — mockup verisinden BİREBİR türetilmiş,
 * dış bağımlılığı olmayan SAF veri (Planlama - Haftalık QURR.dc.html:271-289
 * `data()`, hesaplar `calc()`/`sum()` ile AYNI aritmetik; a-r kolonları ve
 * ara toplamlar burada python ile önceden hesaplanıp string'e çevrildi —
 * motorun kendisi TEKRAR YAZILMADI, yalnız görünür bir örnek üretildi).
 *
 * Şema alanları (`parent_id`, `q_band`/`r_band`, `changed_qty` vb.) EV-BORC-3
 * ile gelen GERÇEK backend alanlarıdır; istemci burada hiçbir şey TÜRETMEZ.
 *
 * `QURR_FIXTURE_READY` — Hafta 21, veri dolu (Q ekranının "ekran" hâli).
 * `QURR_FIXTURE_EMPTY` — Hafta 22, henüz gönderilmiş günlük yok (Q:122-129).
 */
export const QURR_FIXTURE_READY: EvQurrReport = {
  report_date: "2026-09-24",
  week_no: 21,
  week_start: "2026-09-18",
  week_end: "2026-09-24",
  calendar_start: "2026-01-05",
  calendar_end: "2026-12-31",
  last_week_no: 21,
  generated_at: "2026-09-24T16:05:00Z",
  has_field_data: true,
  draft_diary_dates: ["2026-09-21", "2026-09-23"],
  revision: { id: "rev-1", name: "Rev 1", number: 1, frozen_at: "2026-07-02T00:00:00Z" },
  previous_revision: { id: "rev-0", name: "Rev 0", number: 0, frozen_at: "2026-04-28T00:00:00Z" },
  pf_bands: {
    cumulative: { red_below: "0.95", green_from: "1.00", high_above: null },
    daily: { red_below: "0.95", green_from: "0.95", high_above: "1.05" },
  },
  warnings: [],
  kpis: [
  {
      scope: "overall_own",
      pf_cum: "0.98686",
      pf_cum_band: "amber",
      pf_week: "1.058285",
      pf_week_band: "green",
    },
    {
      scope: "overall_subcon",
      pf_cum: "0.907787",
      pf_cum_band: "red",
      pf_week: "0.949694",
      pf_week_band: "amber",
    }  ],
  composites: [
    {
      id: "pacal-beton",
      name: "1 m³ beton başına toplam betonarme a-s",
      measure: "spent",
      unit: "a-s/m³",
      numerator_names: ["Kalıp", "Demir", "Beton döküm"],
      denominator_name: "Beton döküm m³",
      actual: "5.4248",
      planned: "5.288462",
      deviation: "0.02578",
    },
    {
      id: "pacal-duvar",
      name: "1 m² duvar başına duvar + sıva a-s",
      measure: "spent",
      unit: "a-s/m²",
      numerator_names: ["Tuğla duvar", "İç sıva"],
      denominator_name: "Tuğla duvar m²",
      actual: "0.945385",
      planned: "0.994444",
      deviation: "-0.049334",
    },
    {
      id: "pacal-elektrik",
      name: "1 adet buat/priz başına elektrik a-s",
      measure: "spent",
      unit: "a-s/adet",
      numerator_names: ["Kablo çekimi", "Buat/priz montajı"],
      denominator_name: "Buat/priz montajı adet",
      actual: "2.677059",
      planned: "3",
      deviation: "-0.107647",
    },
  ],
  rows: [
  {
      node_id: "KAB.01.01",
      parent_id: "KAB.01",
      code: "KAB.01.01",
      name: "Kalıp",
      uom: "m²",
      level: 3,
      is_direct: true,
      contractor_type: null,
      a_prev_qty: "13600",
      b_qty: "14000",
      c_qty_cum: "6900",
      d_remaining_qty: "7100",
      e_qty_week: "565",
      f_prev_budget_mhr: "11560",
      g_budget_mhr: "11900",
      h_earned_cum: "5865",
      i_spent_cum: "5924",
      j_remaining_mhr: "6035",
      k_earned_week: "480.25",
      l_spent_week: "470",
      m_prev_unit_mhr: "0.85",
      n_unit_mhr: "0.85",
      o_actual_unit_mhr_cum: "0.858551",
      p_actual_unit_mhr_week: "0.831858",
      q_pf_cum: "0.990041",
      q_band: "amber",
      r_pf_week: "1.021809",
      r_band: "green",
      changed_qty: true,
      changed_rate: false,
      changed_budget: true,
    },
    {
      node_id: "KAB.01.02",
      parent_id: "KAB.01",
      code: "KAB.01.02",
      name: "Demir",
      uom: "ton",
      level: 3,
      is_direct: true,
      contractor_type: null,
      a_prev_qty: "520",
      b_qty: "520",
      c_qty_cum: "250",
      d_remaining_qty: "270",
      e_qty_week: "20",
      f_prev_budget_mhr: "5980",
      g_budget_mhr: "6240",
      h_earned_cum: "3000",
      i_spent_cum: "3158",
      j_remaining_mhr: "3240",
      k_earned_week: "240",
      l_spent_week: "250",
      m_prev_unit_mhr: "11.5",
      n_unit_mhr: "12",
      o_actual_unit_mhr_cum: "12.632",
      p_actual_unit_mhr_week: "12.5",
      q_pf_cum: "0.949968",
      q_band: "amber",
      r_pf_week: "0.96",
      r_band: "amber",
      changed_qty: false,
      changed_rate: true,
      changed_budget: true,
    },
    {
      node_id: "KAB.01.03",
      parent_id: "KAB.01",
      code: "KAB.01.03",
      name: "Beton döküm",
      uom: "m³",
      level: 3,
      is_direct: true,
      contractor_type: null,
      a_prev_qty: "5200",
      b_qty: "5200",
      c_qty_cum: "2500",
      d_remaining_qty: "2700",
      e_qty_week: "222",
      f_prev_budget_mhr: "9360",
      g_budget_mhr: "9360",
      h_earned_cum: "4500",
      i_spent_cum: "4480",
      j_remaining_mhr: "4860",
      k_earned_week: "399.6",
      l_spent_week: "330",
      m_prev_unit_mhr: "1.8",
      n_unit_mhr: "1.8",
      o_actual_unit_mhr_cum: "1.792",
      p_actual_unit_mhr_week: "1.486486",
      q_pf_cum: "1.004464",
      q_band: "green",
      r_pf_week: "1.210909",
      r_band: "green",
      changed_qty: false,
      changed_rate: false,
      changed_budget: false,
    },
    {
      node_id: "DUV.01.01",
      parent_id: "DUV.01",
      code: "DUV.01.01",
      name: "Tuğla duvar",
      uom: "m²",
      level: 3,
      is_direct: true,
      contractor_type: null,
      a_prev_qty: "9000",
      b_qty: "9000",
      c_qty_cum: "2600",
      d_remaining_qty: "6400",
      e_qty_week: "273",
      f_prev_budget_mhr: "4950",
      g_budget_mhr: "4950",
      h_earned_cum: "1430",
      i_spent_cum: "1625",
      j_remaining_mhr: "3520",
      k_earned_week: "150.15",
      l_spent_week: "170",
      m_prev_unit_mhr: "0.55",
      n_unit_mhr: "0.55",
      o_actual_unit_mhr_cum: "0.625",
      p_actual_unit_mhr_week: "0.622711",
      q_pf_cum: "0.88",
      q_band: "red",
      r_pf_week: "0.883235",
      r_band: "red",
      changed_qty: false,
      changed_rate: false,
      changed_budget: false,
    },
    {
      node_id: "DUV.02.01",
      parent_id: "DUV.02",
      code: "DUV.02.01",
      name: "İç sıva",
      uom: "m²",
      level: 3,
      is_direct: true,
      contractor_type: null,
      a_prev_qty: "16000",
      b_qty: "16000",
      c_qty_cum: "2800",
      d_remaining_qty: "13200",
      e_qty_week: "440",
      f_prev_budget_mhr: "4000",
      g_budget_mhr: "4000",
      h_earned_cum: "700",
      i_spent_cum: "833",
      j_remaining_mhr: "3300",
      k_earned_week: "110",
      l_spent_week: "115",
      m_prev_unit_mhr: "0.25",
      n_unit_mhr: "0.25",
      o_actual_unit_mhr_cum: "0.2975",
      p_actual_unit_mhr_week: "0.261364",
      q_pf_cum: "0.840336",
      q_band: "red",
      r_pf_week: "0.956522",
      r_band: "amber",
      changed_qty: false,
      changed_rate: false,
      changed_budget: false,
    },
    {
      node_id: "MEK.01.01",
      parent_id: "MEK.01",
      code: "MEK.01.01",
      name: "Pis su borusu",
      uom: "m",
      level: 3,
      is_direct: true,
      contractor_type: null,
      a_prev_qty: "3200",
      b_qty: "3200",
      c_qty_cum: "1450",
      d_remaining_qty: "1750",
      e_qty_week: "138",
      f_prev_budget_mhr: "2400",
      g_budget_mhr: "2560",
      h_earned_cum: "1160",
      i_spent_cum: "1196",
      j_remaining_mhr: "1400",
      k_earned_week: "110.4",
      l_spent_week: "105",
      m_prev_unit_mhr: "0.75",
      n_unit_mhr: "0.8",
      o_actual_unit_mhr_cum: "0.824828",
      p_actual_unit_mhr_week: "0.76087",
      q_pf_cum: "0.9699",
      q_band: "amber",
      r_pf_week: "1.051429",
      r_band: "green",
      changed_qty: false,
      changed_rate: true,
      changed_budget: true,
    },
    {
      node_id: "MEK.01.02",
      parent_id: "MEK.01",
      code: "MEK.01.02",
      name: "Temiz su borusu",
      uom: "m",
      level: 3,
      is_direct: true,
      contractor_type: null,
      a_prev_qty: "4000",
      b_qty: "4000",
      c_qty_cum: "1900",
      d_remaining_qty: "2100",
      e_qty_week: "158",
      f_prev_budget_mhr: "2400",
      g_budget_mhr: "2400",
      h_earned_cum: "1140",
      i_spent_cum: "1226",
      j_remaining_mhr: "1260",
      k_earned_week: "94.8",
      l_spent_week: "100",
      m_prev_unit_mhr: "0.6",
      n_unit_mhr: "0.6",
      o_actual_unit_mhr_cum: "0.645263",
      p_actual_unit_mhr_week: "0.632911",
      q_pf_cum: "0.929853",
      q_band: "red",
      r_pf_week: "0.948",
      r_band: "amber",
      changed_qty: false,
      changed_rate: false,
      changed_budget: false,
    },
    {
      node_id: "ELK.01.01",
      parent_id: "ELK.01",
      code: "ELK.01.01",
      name: "Kablo çekimi",
      uom: "m",
      level: 3,
      is_direct: true,
      contractor_type: null,
      a_prev_qty: "18000",
      b_qty: "18000",
      c_qty_cum: "9800",
      d_remaining_qty: "8200",
      e_qty_week: "900",
      f_prev_budget_mhr: "3600",
      g_budget_mhr: "3600",
      h_earned_cum: "1960",
      i_spent_cum: "1922",
      j_remaining_mhr: "1640",
      k_earned_week: "180",
      l_spent_week: "170",
      m_prev_unit_mhr: "0.2",
      n_unit_mhr: "0.2",
      o_actual_unit_mhr_cum: "0.196122",
      p_actual_unit_mhr_week: "0.188889",
      q_pf_cum: "1.019771",
      q_band: "green",
      r_pf_week: "1.058824",
      r_band: "green",
      changed_qty: false,
      changed_rate: false,
      changed_budget: false,
    },
    {
      node_id: "ELK.01.02",
      parent_id: "ELK.01",
      code: "ELK.01.02",
      name: "Buat/priz montajı",
      uom: "adet",
      level: 3,
      is_direct: true,
      contractor_type: null,
      a_prev_qty: "2400",
      b_qty: "2400",
      c_qty_cum: "1700",
      d_remaining_qty: "700",
      e_qty_week: "100",
      f_prev_budget_mhr: "3600",
      g_budget_mhr: "3600",
      h_earned_cum: "2550",
      i_spent_cum: "2629",
      j_remaining_mhr: "1050",
      k_earned_week: "150",
      l_spent_week: "150",
      m_prev_unit_mhr: "1.5",
      n_unit_mhr: "1.5",
      o_actual_unit_mhr_cum: "1.546471",
      p_actual_unit_mhr_week: "1.5",
      q_pf_cum: "0.969951",
      q_band: "amber",
      r_pf_week: "1",
      r_band: "green",
      changed_qty: false,
      changed_rate: false,
      changed_budget: false,
    },
    {
      node_id: "GEN.01.01",
      parent_id: "GEN.01",
      code: "GEN.01.01",
      name: "Mobilizasyon",
      uom: "gtr",
      level: 3,
      is_direct: false,
      contractor_type: null,
      a_prev_qty: "1",
      b_qty: "1",
      c_qty_cum: "1",
      d_remaining_qty: "0",
      e_qty_week: "0",
      f_prev_budget_mhr: "1400",
      g_budget_mhr: "1400",
      h_earned_cum: "1400",
      i_spent_cum: "1240",
      j_remaining_mhr: "0",
      k_earned_week: "0",
      l_spent_week: "0",
      m_prev_unit_mhr: "1400",
      n_unit_mhr: "1400",
      o_actual_unit_mhr_cum: "1240",
      p_actual_unit_mhr_week: null,
      q_pf_cum: "1.129032",
      q_band: "green",
      r_pf_week: null,
      r_band: null,
      changed_qty: false,
      changed_rate: false,
      changed_budget: false,
    },
    {
      node_id: "GEN.01.02",
      parent_id: "GEN.01",
      code: "GEN.01.02",
      name: "Şantiye temizliği",
      uom: "ay",
      level: 3,
      is_direct: false,
      contractor_type: null,
      a_prev_qty: "11",
      b_qty: "11",
      c_qty_cum: "4.6",
      d_remaining_qty: "6.4",
      e_qty_week: "0.23",
      f_prev_budget_mhr: "1320",
      g_budget_mhr: "1320",
      h_earned_cum: "552",
      i_spent_cum: "860",
      j_remaining_mhr: "768",
      k_earned_week: "27.6",
      l_spent_week: "45",
      m_prev_unit_mhr: "120",
      n_unit_mhr: "120",
      o_actual_unit_mhr_cum: "186.956522",
      p_actual_unit_mhr_week: "195.652174",
      q_pf_cum: "0.64186",
      q_band: "red",
      r_pf_week: "0.613333",
      r_band: "red",
      changed_qty: false,
      changed_rate: false,
      changed_budget: false,
    }  ],
  totals: [
  {
      kind: "discipline",
      node_id: "KAB",
      parent_id: null,
      code: "KAB",
      name: "Kaba İnşaat",
      contractor_mix: "Kendi",
      f_prev_budget_mhr: "26900",
      g_budget_mhr: "27500",
      h_earned_cum: "13365",
      i_spent_cum: "13562",
      j_remaining_mhr: "14135",
      k_earned_week: "1119.85",
      l_spent_week: "1050",
      q_pf_cum: "0.985474",
      q_band: "amber",
      r_pf_week: "1.066524",
      r_band: "green",
    },
    {
      kind: "group",
      node_id: "KAB.01",
      parent_id: "KAB",
      code: "KAB.01",
      name: "Betonarme",
      contractor_mix: null,
      f_prev_budget_mhr: "26900",
      g_budget_mhr: "27500",
      h_earned_cum: "13365",
      i_spent_cum: "13562",
      j_remaining_mhr: "14135",
      k_earned_week: "1119.85",
      l_spent_week: "1050",
      q_pf_cum: "0.985474",
      q_band: "amber",
      r_pf_week: "1.066524",
      r_band: "green",
    },
    {
      kind: "discipline",
      node_id: "DUV",
      parent_id: null,
      code: "DUV",
      name: "Duvar & Sıva",
      contractor_mix: "Taşeron",
      f_prev_budget_mhr: "8950",
      g_budget_mhr: "8950",
      h_earned_cum: "2130",
      i_spent_cum: "2458",
      j_remaining_mhr: "6820",
      k_earned_week: "260.15",
      l_spent_week: "285",
      q_pf_cum: "0.866558",
      q_band: "red",
      r_pf_week: "0.912807",
      r_band: "red",
    },
    {
      kind: "group",
      node_id: "DUV.01",
      parent_id: "DUV",
      code: "DUV.01",
      name: "Duvar",
      contractor_mix: null,
      f_prev_budget_mhr: "4950",
      g_budget_mhr: "4950",
      h_earned_cum: "1430",
      i_spent_cum: "1625",
      j_remaining_mhr: "3520",
      k_earned_week: "150.15",
      l_spent_week: "170",
      q_pf_cum: "0.88",
      q_band: "red",
      r_pf_week: "0.883235",
      r_band: "red",
    },
    {
      kind: "group",
      node_id: "DUV.02",
      parent_id: "DUV",
      code: "DUV.02",
      name: "Sıva",
      contractor_mix: null,
      f_prev_budget_mhr: "4000",
      g_budget_mhr: "4000",
      h_earned_cum: "700",
      i_spent_cum: "833",
      j_remaining_mhr: "3300",
      k_earned_week: "110",
      l_spent_week: "115",
      q_pf_cum: "0.840336",
      q_band: "red",
      r_pf_week: "0.956522",
      r_band: "amber",
    },
    {
      kind: "discipline",
      node_id: "MEK",
      parent_id: null,
      code: "MEK",
      name: "Mekanik Tesisat",
      contractor_mix: "Taşeron",
      f_prev_budget_mhr: "4800",
      g_budget_mhr: "4960",
      h_earned_cum: "2300",
      i_spent_cum: "2422",
      j_remaining_mhr: "2660",
      k_earned_week: "205.2",
      l_spent_week: "205",
      q_pf_cum: "0.949628",
      q_band: "amber",
      r_pf_week: "1.000976",
      r_band: "green",
    },
    {
      kind: "group",
      node_id: "MEK.01",
      parent_id: "MEK",
      code: "MEK.01",
      name: "Sıhhi tesisat",
      contractor_mix: null,
      f_prev_budget_mhr: "4800",
      g_budget_mhr: "4960",
      h_earned_cum: "2300",
      i_spent_cum: "2422",
      j_remaining_mhr: "2660",
      k_earned_week: "205.2",
      l_spent_week: "205",
      q_pf_cum: "0.949628",
      q_band: "amber",
      r_pf_week: "1.000976",
      r_band: "green",
    },
    {
      kind: "discipline",
      node_id: "ELK",
      parent_id: null,
      code: "ELK",
      name: "Elektrik",
      contractor_mix: "Kendi",
      f_prev_budget_mhr: "7200",
      g_budget_mhr: "7200",
      h_earned_cum: "4510",
      i_spent_cum: "4551",
      j_remaining_mhr: "2690",
      k_earned_week: "330",
      l_spent_week: "320",
      q_pf_cum: "0.990991",
      q_band: "amber",
      r_pf_week: "1.03125",
      r_band: "green",
    },
    {
      kind: "group",
      node_id: "ELK.01",
      parent_id: "ELK",
      code: "ELK.01",
      name: "Kuvvetli akım",
      contractor_mix: null,
      f_prev_budget_mhr: "7200",
      g_budget_mhr: "7200",
      h_earned_cum: "4510",
      i_spent_cum: "4551",
      j_remaining_mhr: "2690",
      k_earned_week: "330",
      l_spent_week: "320",
      q_pf_cum: "0.990991",
      q_band: "amber",
      r_pf_week: "1.03125",
      r_band: "green",
    },
    {
      kind: "direct_total",
      node_id: null,
      parent_id: null,
      code: "Σ D",
      name: "Doğrudan toplam",
      contractor_mix: null,
      f_prev_budget_mhr: "47850",
      g_budget_mhr: "48610",
      h_earned_cum: "22305",
      i_spent_cum: "22993",
      j_remaining_mhr: "26305",
      k_earned_week: "1915.2",
      l_spent_week: "1860",
      q_pf_cum: "0.970078",
      q_band: "amber",
      r_pf_week: "1.029677",
      r_band: "green",
    },
    {
      kind: "discipline",
      node_id: "GEN",
      parent_id: null,
      code: "GEN",
      name: "Genel / Dolaylı",
      contractor_mix: null,
      f_prev_budget_mhr: "2720",
      g_budget_mhr: "2720",
      h_earned_cum: "1952",
      i_spent_cum: "2100",
      j_remaining_mhr: "768",
      k_earned_week: "27.6",
      l_spent_week: "45",
      q_pf_cum: "0.929524",
      q_band: "red",
      r_pf_week: "0.613333",
      r_band: "red",
    },
    {
      kind: "group",
      node_id: "GEN.01",
      parent_id: "GEN",
      code: "GEN.01",
      name: "Şantiye genel",
      contractor_mix: null,
      f_prev_budget_mhr: "2720",
      g_budget_mhr: "2720",
      h_earned_cum: "1952",
      i_spent_cum: "2100",
      j_remaining_mhr: "768",
      k_earned_week: "27.6",
      l_spent_week: "45",
      q_pf_cum: "0.929524",
      q_band: "red",
      r_pf_week: "0.613333",
      r_band: "red",
    },
    {
      kind: "all_total",
      node_id: null,
      parent_id: null,
      code: "Σ D+DL",
      name: "Doğrudan + Dolaylı toplam",
      contractor_mix: null,
      f_prev_budget_mhr: "50570",
      g_budget_mhr: "51330",
      h_earned_cum: "24257",
      i_spent_cum: "25093",
      j_remaining_mhr: "27073",
      k_earned_week: "1942.8",
      l_spent_week: "1905",
      q_pf_cum: "0.966684",
      q_band: "amber",
      r_pf_week: "1.019843",
      r_band: "green",
    }  ],
};

/** Q:122-129 — Hafta 22, henüz gönderilmiş günlük yok. */
export const QURR_FIXTURE_EMPTY: EvQurrReport = {
  report_date: "2026-09-24",
  week_no: 22,
  week_start: "2026-09-25",
  week_end: "2026-10-01",
  calendar_start: "2026-01-05",
  calendar_end: "2026-12-31",
  last_week_no: 21,
  generated_at: null,
  has_field_data: false,
  draft_diary_dates: [],
  revision: { id: "rev-1", name: "Rev 1", number: 1, frozen_at: "2026-07-02T00:00:00Z" },
  previous_revision: { id: "rev-0", name: "Rev 0", number: 0, frozen_at: "2026-04-28T00:00:00Z" },
  pf_bands: null,
  warnings: [],
  kpis: [],
  composites: [],
  rows: [],
  totals: [],
};
