import type { EvDailyReport, EvQtyTreeRow, EvWarning } from "@/lib/api/models";

/**
 * PLN-F3.4 · GİR fikstürleri — `Planlama - Günlük İlerleme Raporu.dc.html`
 * verisinden (disiplinler, iş tipleri, hafta) TÜRETİLMİŞ, tipli
 * `EvDailyReport` örnekleri. Üç varyant: taslak (bugün, eksik günlük bandı
 * açık), onaylı (S13 sürüm eki), üretilemedi (S11 "günlüğü yok").
 */

const WEATHER = [
  { day: "2026-09-18", condition: "sunny", temp_min_c: "11", temp_max_c: "18", wind_ms: "5" },
  { day: "2026-09-19", condition: "sunny", temp_min_c: "10", temp_max_c: "17", wind_ms: "4.5" },
  { day: "2026-09-20", condition: "cloudy", temp_min_c: "13", temp_max_c: "16", wind_ms: "3.6" },
  { day: "2026-09-21", condition: "windy", temp_min_c: "8", temp_max_c: "15", wind_ms: "8.3" },
  { day: "2026-09-22", condition: "rainy", temp_min_c: "6", temp_max_c: "14", wind_ms: "5" },
  { day: "2026-09-23", condition: "cloudy", temp_min_c: "8", temp_max_c: "15", wind_ms: "3.9" },
  { day: "2026-09-24", condition: "partly_cloudy", temp_min_c: "9", temp_max_c: "17", wind_ms: "4.2" },
];

const KPIS: EvDailyReport["kpis"] = [
  {
    kind: "overall",
    budget_mhr: "48610",
    pf_week: "0.95",
    pf_week_band: "green",
    node_id: null,
    name: "Genel",
    contractor_mix: null,
    planned_pct_day: "0.6135",
    progress_pct_day: "0.6845",
    spent_day: "310",
    earned_day: "212.11",
    pf_day: "0.68",
    pf_day_band: "red",
    pf_cum: "0.94",
    pf_cum_band: "amber",
    planned_pct_cum: "0.4848",
    progress_pct_cum: "0.4586",
    spent_cum: "45680",
    earned_cum: "22305",
    variance: "-0.0262",
    status: "late",
  },
  {
    kind: "overall_own",
    budget_mhr: "31200",
    pf_week: "0.97",
    pf_week_band: "green",
    node_id: null,
    name: "Genel – Kendi",
    contractor_mix: null,
    planned_pct_day: "0.6538",
    progress_pct_day: "0.72",
    spent_day: "220",
    earned_day: "160.14",
    pf_day: "0.73",
    pf_day_band: "amber",
    pf_cum: "0.96",
    pf_cum_band: "green",
    planned_pct_cum: "0.51",
    progress_pct_cum: "0.49",
    spent_cum: "31200",
    earned_cum: "15408",
    variance: "-0.02",
    status: "late",
  },
  {
    kind: "overall_subcon",
    budget_mhr: "17410",
    pf_week: "0.91",
    pf_week_band: "red",
    node_id: null,
    name: "Genel – Taşeron",
    contractor_mix: null,
    planned_pct_day: "0.53",
    progress_pct_day: "0.61",
    spent_day: "90",
    earned_day: "51.97",
    pf_day: "0.58",
    pf_day_band: "red",
    pf_cum: "0.90",
    pf_cum_band: "red",
    planned_pct_cum: "0.44",
    progress_pct_cum: "0.40",
    spent_cum: "14480",
    earned_cum: "6897",
    variance: "-0.04",
    status: "late",
  },
  {
    kind: "discipline",
    budget_mhr: "18800",
    pf_week: "0.96",
    pf_week_band: "green",
    node_id: "d:KAB",
    name: "Kaba İnşaat",
    contractor_mix: "own",
    planned_pct_day: "0.63",
    progress_pct_day: "0.71",
    spent_day: "168",
    earned_day: "119.6",
    pf_day: "0.71",
    pf_day_band: "amber",
    pf_cum: "0.97",
    pf_cum_band: "green",
    planned_pct_cum: "0.5",
    progress_pct_cum: "0.48",
    spent_cum: "18400",
    earned_cum: "9028",
    variance: "-0.02",
    status: "normal",
  },
  {
    kind: "discipline",
    budget_mhr: "8200",
    pf_week: "0.89",
    pf_week_band: "red",
    node_id: "d:DUV",
    name: "Duvar & Sıva",
    contractor_mix: "subcon",
    planned_pct_day: "0.52",
    progress_pct_day: "0.6",
    spent_day: "62",
    earned_day: "37.2",
    pf_day: "0.6",
    pf_day_band: "red",
    pf_cum: "0.88",
    pf_cum_band: "red",
    planned_pct_cum: "0.4",
    progress_pct_cum: "0.35",
    spent_cum: "7200",
    earned_cum: "3168",
    variance: "-0.05",
    status: "late",
  },
];

const QUANTITIES: EvQtyTreeRow[] = [
  {
    node_id: "d:KAB",
    level: 1,
    name: "Kaba İnşaat",
    uom: null,
    contractor_type: "own",
    is_direct: null,
    pf_day: "0.71",
    pf_day_band: "amber",
    pf_cum: "0.97",
    pf_cum_band: "green",
    planned_qty: null,
    planned_unit_mhr: null,
    progress_pct_cum: "0.48",
    qty_cum: null,
    qty_day: null,
    remaining_qty: null,
    spent_day: "168",
    actual_unit_mhr_cum: null,
    actual_unit_mhr_day: null,
  },
  {
    node_id: "i:kalip",
    level: 2,
    name: "Kalıp",
    uom: "m²",
    contractor_type: "own",
    is_direct: true,
    pf_day: "0.93",
    pf_day_band: "amber",
    pf_cum: "0.518",
    pf_cum_band: "red",
    planned_qty: "14000",
    planned_unit_mhr: "0.85",
    progress_pct_cum: "0.4229",
    qty_cum: "5924",
    qty_day: "93",
    remaining_qty: "8076",
    spent_day: "76.18",
    actual_unit_mhr_cum: "0.8189",
    actual_unit_mhr_day: "0.8191",
  },
  {
    node_id: "i:demir",
    level: 2,
    name: "Demir",
    uom: "ton",
    contractor_type: "own",
    is_direct: true,
    pf_day: "0.50",
    pf_day_band: "red",
    pf_cum: "0.61",
    pf_cum_band: "red",
    planned_qty: "520",
    planned_unit_mhr: "12",
    progress_pct_cum: "0.4808",
    qty_cum: "250",
    qty_day: "3.4",
    remaining_qty: "270",
    spent_day: "41.16",
    actual_unit_mhr_cum: "19.7",
    actual_unit_mhr_day: "12.11",
  },
  {
    node_id: "d:DUV",
    level: 1,
    name: "Duvar & Sıva",
    uom: null,
    contractor_type: "subcon",
    is_direct: null,
    pf_day: "0.6",
    pf_day_band: "red",
    pf_cum: "0.88",
    pf_cum_band: "red",
    planned_qty: null,
    planned_unit_mhr: null,
    progress_pct_cum: "0.35",
    qty_cum: null,
    qty_day: null,
    remaining_qty: null,
    spent_day: "62",
    actual_unit_mhr_cum: null,
    actual_unit_mhr_day: null,
  },
  {
    node_id: "i:tugla",
    level: 2,
    name: "Tuğla duvar",
    uom: "m²",
    contractor_type: "subcon",
    is_direct: true,
    pf_day: "0.62",
    pf_day_band: "red",
    pf_cum: "0.90",
    pf_cum_band: "red",
    planned_qty: "9000",
    planned_unit_mhr: "0.55",
    progress_pct_cum: "0.1806",
    qty_cum: "1625",
    qty_day: "52",
    remaining_qty: "7375",
    spent_day: "32",
    actual_unit_mhr_cum: "0.5978",
    actual_unit_mhr_day: "0.6154",
  },
];

const TREND: EvDailyReport["trend"] = [
  { day: "2026-09-18", planned_pct_cum: "0.42", progress_pct_cum: "0.4590", delta: "0.0390", is_holiday: false, is_draft: false, is_future: false, earned_day: "318", spent_day: "310", pf_day: "1.03", pf_rolling: "0.98" },
  { day: "2026-09-19", planned_pct_cum: "0.4262", progress_pct_cum: "0.4650", delta: "0.0388", is_holiday: false, is_draft: false, is_future: false, earned_day: "290", spent_day: "295", pf_day: "0.98", pf_rolling: "0.98" },
  { day: "2026-09-20", planned_pct_cum: "0.4262", progress_pct_cum: "0.4650", delta: "0.0388", is_holiday: true, is_draft: false, is_future: false, earned_day: "0", spent_day: "0", pf_day: null, pf_rolling: "0.98" },
  { day: "2026-09-21", planned_pct_cum: "0.4324", progress_pct_cum: "0.4720", delta: "0.0396", is_holiday: false, is_draft: true, is_future: false, earned_day: "335", spent_day: "340", pf_day: "0.99", pf_rolling: "0.97" },
  { day: "2026-09-22", planned_pct_cum: "0.4386", progress_pct_cum: "0.4520", delta: "0.0134", is_holiday: false, is_draft: false, is_future: false, earned_day: "322", spent_day: "330", pf_day: "0.98", pf_rolling: "0.97" },
  { day: "2026-09-23", planned_pct_cum: "0.4448", progress_pct_cum: "0.4520", delta: "0.0072", is_holiday: false, is_draft: true, is_future: false, earned_day: "328", spent_day: "333", pf_day: "0.99", pf_rolling: "0.97" },
  { day: "2026-09-24", planned_pct_cum: "0.4848", progress_pct_cum: "0.4586", delta: "-0.0262", is_holiday: false, is_draft: false, is_future: false, earned_day: "322", spent_day: "310", pf_day: "1.04", pf_rolling: "0.97" },
];

const UNRATED_ENTRIES: EvWarning[] = [
  {
    code: "unrated_entry",
    target: "leaf",
    target_id: "i:buat-priz",
    message: "Buat/priz montajı için oran tanımlı değil",
    item_name: "Buat/priz montajı",
    section_name: "Elektrik",
    uom: "adet",
    value: "6",
  },
];

const PF_OUT_OF_BAND: EvWarning[] = [
  {
    code: "pf_out_of_band",
    target: "leaf",
    target_id: "i:demir",
    message: "Demir günlük PF bant dışı",
    item_name: "Demir",
    section_name: "Kaba İnşaat",
    value: "0.50",
  },
  {
    code: "pf_out_of_band",
    target: "leaf",
    target_id: "i:tugla",
    message: "Tuğla duvar günlük PF bant dışı",
    item_name: "Tuğla duvar",
    section_name: "Duvar & Sıva",
    value: "0.62",
  },
];

const BASE: Omit<EvDailyReport, "status" | "approved_at" | "approved_by" | "version" | "draft_diary_dates" | "missing_diary_dates" | "report_date"> = {
  calendar_start: "2026-05-06",
  calendar_end: "2027-03-30",
  day_no: 142,
  footer: {
    spent_total_day: "310",
    timesheet_total_day: "326",
    undistributed_day: "16",
    unallocated_day: "0",
    undistributed_reason: "yardımcılar genel temizlikte",
  },
  generated_at: "2026-09-24T18:40:00+03:00",
  kpis: KPIS,
  pf_bands: {
    daily: { red_below: "0.95", green_from: "0.95", high_above: "1.05" },
    cumulative: { red_below: "0.95", green_from: "1.00", high_above: null },
  },
  project_start: "2026-05-06",
  quantities: QUANTITIES,
  report_no: 142,
  revision: { id: "rev-1", name: "Rev 1", number: 1, frozen_at: "2026-05-01T09:00:00+03:00" },
  tolerance_points: "2.0",
  trend: TREND,
  unrated_entries: UNRATED_ENTRIES,
  warnings: PF_OUT_OF_BAND,
  weather: WEATHER,
  week_end: "2026-09-24",
  week_no: 21,
  week_start: "2026-09-18",
};

/** Taslak — S10 bandı açık (`draft_diary_dates` dolu), onay PASİF. */
export const DAILY_REPORT_FIXTURE_DRAFT: EvDailyReport = {
  ...BASE,
  report_date: "2026-09-24",
  status: "draft",
  approved_at: null,
  approved_by: null,
  version: null,
  draft_diary_dates: ["2026-09-21", "2026-09-23"],
  missing_diary_dates: [],
};

/** Onaylı — S13 "· sürüm n", araç çubuğu salt okunur. */
export const DAILY_REPORT_FIXTURE_APPROVED: EvDailyReport = {
  ...BASE,
  report_date: "2026-09-22",
  status: "approved",
  approved_at: "2026-09-23T08:47:00+03:00",
  approved_by: { id: "u-mehmet", full_name: "Mehmet Kaya" },
  version: 1,
  draft_diary_dates: [],
  missing_diary_dates: [],
};

/** Üretilemedi — S11 "günlüğü yok" (o gün hiç günlük gönderilmedi). */
export const DAILY_REPORT_FIXTURE_NOT_GENERATED: EvDailyReport = {
  ...BASE,
  report_date: "2026-09-25",
  status: "not_generated",
  approved_at: null,
  approved_by: null,
  version: null,
  draft_diary_dates: [],
  missing_diary_dates: ["2026-09-25"],
  kpis: [],
  quantities: [],
  trend: [],
  footer: null,
  unrated_entries: [],
  warnings: [],
};
