import type { EvDailyReport, EvQtyTreeRow, EvWarning } from "@/lib/api/models";

/**
 * PLN-F3.4 (F3.6b lider denetimi 3. tur) - GIR fiksturleri mockup JS'inden
 * (data()/agg()/renderVals(), 24.09.2026 taslak hali) BIREBIR TURETILDI:
 * 4 disiplin, L2 alt gruplar, 9 is tipi. Tum sayilar python Decimal ile
 * mockup formulleriyle (bud=pq*rate, ce=cq*rate, de=dq*rate, pf=de/ds,
 * pf_cum=ce/cs) YENIDEN hesaplandi.
 */

// F3.6b lider denetimi (4. tur, bölge kırpıntısı) — mockup `W` dizisi (dc.html:502)
// rüzgârı DOĞRUDAN km/sa basar (`{{ w.wind }} km/s`, dönüşüm YOK); ekran ise
// `formatWindKmh` (m/s→km/h ×3.6, çekirdek kanon) kullanır — `wind_ms` bu
// yüzden mockup değerinin /3.6'sı (round-trip: Math.round(wind_ms*3.6) === mockup).
const WEATHER = [
  { day: "2026-09-18", condition: "sunny", temp_min_c: "18", temp_max_c: "29", wind_ms: "3.0556" }, // 11 km/sa
  { day: "2026-09-19", condition: "sunny", temp_min_c: "17", temp_max_c: "30", wind_ms: "2.7778" }, // 10 km/sa
  { day: "2026-09-20", condition: "partly_cloudy", temp_min_c: "16", temp_max_c: "27", wind_ms: "3.6111" }, // 13 km/sa
  { day: "2026-09-21", condition: "windy", temp_min_c: "15", temp_max_c: "24", wind_ms: "8.3333" }, // 30 km/sa
  { day: "2026-09-22", condition: "rainy", temp_min_c: "14", temp_max_c: "21", wind_ms: "5" }, // 18 km/sa
  { day: "2026-09-23", condition: "cloudy", temp_min_c: "15", temp_max_c: "24", wind_ms: "3.8889" }, // 14 km/sa
  { day: "2026-09-24", condition: "partly_cloudy", temp_min_c: "17", temp_max_c: "28", wind_ms: "4.1667" }, // 15 km/sa
];

const KPIS: EvDailyReport["kpis"] = [
  {
    kind: "overall",
    node_id: null,
    name: "Genel",
    contractor_mix: null,
    planned_pct_day: "0.006172",
    progress_pct_day: "0.006631",
    spent_day: "310.00",
    spent_cum: "22993.00",
    earned_day: "322.35",
    earned_cum: "22305.00",
    pf_day: "1.039839",
    pf_day_band: "green",
    pf_cum: "0.970078",
    pf_cum_band: "amber",
    planned_pct_cum: "0.484894",
    progress_pct_cum: "0.458856",
    variance: "-0.026038",
    status: "late",
    budget_mhr: "48610.00",
    pf_week: "0.970078",
    pf_week_band: "amber",
  },
  {
    kind: "overall_own",
    node_id: null,
    name: "Genel – Kendi",
    contractor_mix: null,
    planned_pct_day: "0.005994",
    progress_pct_day: "0.006693",
    spent_day: "214.00",
    spent_cum: "18113.00",
    earned_day: "232.25",
    earned_cum: "17875.00",
    pf_day: "1.085280",
    pf_day_band: "high",
    pf_cum: "0.986860",
    pf_cum_band: "amber",
    planned_pct_cum: "0.534392",
    progress_pct_cum: "0.515130",
    variance: "-0.019262",
    status: "normal",
    budget_mhr: "34700.00",
    pf_week: "0.986860",
    pf_week_band: "amber",
  },
  {
    kind: "overall_subcon",
    node_id: null,
    name: "Genel – Taşeron",
    contractor_mix: null,
    planned_pct_day: "0.006614",
    progress_pct_day: "0.006477",
    spent_day: "96.00",
    spent_cum: "4880.00",
    earned_day: "90.10",
    earned_cum: "4430.00",
    pf_day: "0.938542",
    pf_day_band: "red",
    pf_cum: "0.907787",
    pf_cum_band: "red",
    planned_pct_cum: "0.361416",
    progress_pct_cum: "0.318476",
    variance: "-0.042940",
    status: "late",
    budget_mhr: "13910.00",
    pf_week: "0.907787",
    pf_week_band: "red",
  },
  {
    kind: "discipline",
    node_id: "d:KAB",
    name: "Kaba İnşaat",
    contractor_mix: "own",
    planned_pct_day: "0.006109",
    progress_pct_day: "0.006191",
    spent_day: "160.00",
    spent_cum: "13562.00",
    earned_day: "170.25",
    earned_cum: "13365.00",
    pf_day: "1.064063",
    pf_day_band: "high",
    pf_cum: "0.985474",
    pf_cum_band: "amber",
    planned_pct_cum: "0.514596",
    progress_pct_cum: "0.486000",
    variance: "-0.028596",
    status: "late",
    budget_mhr: "27500.00",
    pf_week: "0.985474",
    pf_week_band: "amber",
  },
  {
    kind: "discipline",
    node_id: "d:DUV",
    name: "Duvar & Sıva",
    contractor_mix: "subcon",
    planned_pct_day: "0.006927",
    progress_pct_day: "0.005709",
    spent_day: "56.00",
    spent_cum: "2458.00",
    earned_day: "51.10",
    earned_cum: "2130.00",
    pf_day: "0.912500",
    pf_day_band: "red",
    pf_cum: "0.866558",
    pf_cum_band: "red",
    planned_pct_cum: "0.301061",
    progress_pct_cum: "0.237989",
    variance: "-0.063073",
    status: "late",
    budget_mhr: "8950.00",
    pf_week: "0.866558",
    pf_week_band: "red",
  },
  {
    kind: "discipline",
    node_id: "d:MEK",
    name: "Mekanik Tesisat",
    contractor_mix: "subcon",
    planned_pct_day: "0.006048",
    progress_pct_day: "0.007863",
    spent_day: "40.00",
    spent_cum: "2422.00",
    earned_day: "39.00",
    earned_cum: "2300.00",
    pf_day: "0.975000",
    pf_day_band: "green",
    pf_cum: "0.949628",
    pf_cum_band: "amber",
    planned_pct_cum: "0.470323",
    progress_pct_cum: "0.463710",
    variance: "-0.006613",
    status: "normal",
    budget_mhr: "4960.00",
    pf_week: "0.949628",
    pf_week_band: "amber",
  },
  {
    kind: "discipline",
    node_id: "d:ELK",
    name: "Elektrik",
    contractor_mix: "own",
    planned_pct_day: "0.005556",
    progress_pct_day: "0.008611",
    spent_day: "54.00",
    spent_cum: "4551.00",
    earned_day: "62.00",
    earned_cum: "4510.00",
    pf_day: "1.148148",
    pf_day_band: "high",
    pf_cum: "0.990991",
    pf_cum_band: "amber",
    planned_pct_cum: "0.610000",
    progress_pct_cum: "0.626389",
    variance: "0.016389",
    status: "normal",
    budget_mhr: "7200.00",
    pf_week: "0.990991",
    pf_week_band: "amber",
  },
];

const QUANTITIES: EvQtyTreeRow[] = [
  {
    node_id: "d:KAB",
    level: 1,
    name: "Kaba İnşaat",
    uom: null,
    contractor_type: "own",
    is_direct: null,
    pf_day: "1.0641",
    pf_day_band: "high",
    pf_cum: null,
    pf_cum_band: null,
    planned_qty: null,
    planned_unit_mhr: null,
    progress_pct_cum: "0.486000",
    qty_cum: null,
    qty_day: null,
    remaining_qty: null,
    spent_day: "160.00",
    actual_unit_mhr_cum: null,
    actual_unit_mhr_day: null,
  },
  {
    node_id: "s:kalip-grp",
    level: 2,
    name: "Betonarme",
    uom: null,
    contractor_type: "own",
    is_direct: null,
    pf_day: "1.0641",
    pf_day_band: "high",
    pf_cum: null,
    pf_cum_band: null,
    planned_qty: null,
    planned_unit_mhr: null,
    progress_pct_cum: "0.486000",
    qty_cum: null,
    qty_day: null,
    remaining_qty: null,
    spent_day: "160.00",
    actual_unit_mhr_cum: null,
    actual_unit_mhr_day: null,
  },
  {
    node_id: "i:kalip",
    level: 3,
    name: "Kalıp",
    uom: "m²",
    contractor_type: "own",
    is_direct: true,
    pf_day: "1.0377",
    pf_day_band: "green",
    pf_cum: "0.9900",
    pf_cum_band: "amber",
    planned_qty: "14000.00",
    planned_unit_mhr: "0.8500",
    progress_pct_cum: "0.492857",
    qty_cum: "6900.00",
    qty_day: "93.00",
    remaining_qty: "7100.00",
    spent_day: "76.18",
    actual_unit_mhr_cum: "0.8586",
    actual_unit_mhr_day: "0.8191",
  },
  {
    node_id: "i:demir",
    level: 3,
    name: "Demir",
    uom: "ton",
    contractor_type: "own",
    is_direct: true,
    pf_day: "0.9913",
    pf_day_band: "green",
    pf_cum: "0.9500",
    pf_cum_band: "amber",
    planned_qty: "520.00",
    planned_unit_mhr: "12.0000",
    progress_pct_cum: "0.480769",
    qty_cum: "250.00",
    qty_day: "3.40",
    remaining_qty: "270.00",
    spent_day: "41.16",
    actual_unit_mhr_cum: "12.6320",
    actual_unit_mhr_day: "12.1059",
  },
  {
    node_id: "i:beton-dokum",
    level: 3,
    name: "Beton döküm",
    uom: "m³",
    contractor_type: "own",
    is_direct: true,
    pf_day: "1.1814",
    pf_day_band: "high",
    pf_cum: "1.0045",
    pf_cum_band: "green",
    planned_qty: "5200.00",
    planned_unit_mhr: "1.8000",
    progress_pct_cum: "0.480769",
    qty_cum: "2500.00",
    qty_day: "28.00",
    remaining_qty: "2700.00",
    spent_day: "42.66",
    actual_unit_mhr_cum: "1.7920",
    actual_unit_mhr_day: "1.5236",
  },
  {
    node_id: "d:DUV",
    level: 1,
    name: "Duvar & Sıva",
    uom: null,
    contractor_type: "subcon",
    is_direct: null,
    pf_day: "0.9125",
    pf_day_band: "red",
    pf_cum: null,
    pf_cum_band: null,
    planned_qty: null,
    planned_unit_mhr: null,
    progress_pct_cum: "0.237989",
    qty_cum: null,
    qty_day: null,
    remaining_qty: null,
    spent_day: "56.00",
    actual_unit_mhr_cum: null,
    actual_unit_mhr_day: null,
  },
  {
    node_id: "s:tugla-duvar-grp",
    level: 2,
    name: "Duvar",
    uom: null,
    contractor_type: "subcon",
    is_direct: null,
    pf_day: "0.8938",
    pf_day_band: "red",
    pf_cum: null,
    pf_cum_band: null,
    planned_qty: null,
    planned_unit_mhr: null,
    progress_pct_cum: "0.288889",
    qty_cum: null,
    qty_day: null,
    remaining_qty: null,
    spent_day: "32.00",
    actual_unit_mhr_cum: null,
    actual_unit_mhr_day: null,
  },
  {
    node_id: "i:tugla-duvar",
    level: 3,
    name: "Tuğla duvar",
    uom: "m²",
    contractor_type: "subcon",
    is_direct: true,
    pf_day: "0.8938",
    pf_day_band: "red",
    pf_cum: "0.8800",
    pf_cum_band: "red",
    planned_qty: "9000.00",
    planned_unit_mhr: "0.5500",
    progress_pct_cum: "0.288889",
    qty_cum: "2600.00",
    qty_day: "52.00",
    remaining_qty: "6400.00",
    spent_day: "32.00",
    actual_unit_mhr_cum: "0.6250",
    actual_unit_mhr_day: "0.6154",
  },
  {
    node_id: "s:ic-siva-grp",
    level: 2,
    name: "Sıva",
    uom: null,
    contractor_type: "subcon",
    is_direct: null,
    pf_day: "0.9375",
    pf_day_band: "red",
    pf_cum: null,
    pf_cum_band: null,
    planned_qty: null,
    planned_unit_mhr: null,
    progress_pct_cum: "0.175000",
    qty_cum: null,
    qty_day: null,
    remaining_qty: null,
    spent_day: "24.00",
    actual_unit_mhr_cum: null,
    actual_unit_mhr_day: null,
  },
  {
    node_id: "i:ic-siva",
    level: 3,
    name: "İç sıva",
    uom: "m²",
    contractor_type: "subcon",
    is_direct: true,
    pf_day: "0.9375",
    pf_day_band: "red",
    pf_cum: "0.8403",
    pf_cum_band: "red",
    planned_qty: "16000.00",
    planned_unit_mhr: "0.2500",
    progress_pct_cum: "0.175000",
    qty_cum: "2800.00",
    qty_day: "90.00",
    remaining_qty: "13200.00",
    spent_day: "24.00",
    actual_unit_mhr_cum: "0.2975",
    actual_unit_mhr_day: "0.2667",
  },
  {
    node_id: "d:MEK",
    level: 1,
    name: "Mekanik Tesisat",
    uom: null,
    contractor_type: "subcon",
    is_direct: null,
    pf_day: "0.9750",
    pf_day_band: "green",
    pf_cum: null,
    pf_cum_band: null,
    planned_qty: null,
    planned_unit_mhr: null,
    progress_pct_cum: "0.463710",
    qty_cum: null,
    qty_day: null,
    remaining_qty: null,
    spent_day: "40.00",
    actual_unit_mhr_cum: null,
    actual_unit_mhr_day: null,
  },
  {
    node_id: "s:pis-su-grp",
    level: 2,
    name: "Sıhhi tesisat",
    uom: null,
    contractor_type: "subcon",
    is_direct: null,
    pf_day: "0.9750",
    pf_day_band: "green",
    pf_cum: null,
    pf_cum_band: null,
    planned_qty: null,
    planned_unit_mhr: null,
    progress_pct_cum: "0.463710",
    qty_cum: null,
    qty_day: null,
    remaining_qty: null,
    spent_day: "40.00",
    actual_unit_mhr_cum: null,
    actual_unit_mhr_day: null,
  },
  {
    node_id: "i:pis-su",
    level: 3,
    name: "Pis su borusu",
    uom: "m",
    contractor_type: "subcon",
    is_direct: true,
    pf_day: "1.0000",
    pf_day_band: "green",
    pf_cum: "0.9699",
    pf_cum_band: "amber",
    planned_qty: "3200.00",
    planned_unit_mhr: "0.8000",
    progress_pct_cum: "0.453125",
    qty_cum: "1450.00",
    qty_day: "30.00",
    remaining_qty: "1750.00",
    spent_day: "24.00",
    actual_unit_mhr_cum: "0.8248",
    actual_unit_mhr_day: "0.8000",
  },
  {
    node_id: "i:temiz-su",
    level: 3,
    name: "Temiz su borusu",
    uom: "m",
    contractor_type: "subcon",
    is_direct: true,
    pf_day: "0.9375",
    pf_day_band: "red",
    pf_cum: "0.9299",
    pf_cum_band: "red",
    planned_qty: "4000.00",
    planned_unit_mhr: "0.6000",
    progress_pct_cum: "0.475000",
    qty_cum: "1900.00",
    qty_day: "25.00",
    remaining_qty: "2100.00",
    spent_day: "16.00",
    actual_unit_mhr_cum: "0.6453",
    actual_unit_mhr_day: "0.6400",
  },
  {
    node_id: "d:ELK",
    level: 1,
    name: "Elektrik",
    uom: null,
    contractor_type: "own",
    is_direct: null,
    pf_day: "1.1481",
    pf_day_band: "high",
    pf_cum: null,
    pf_cum_band: null,
    planned_qty: null,
    planned_unit_mhr: null,
    progress_pct_cum: "0.626389",
    qty_cum: null,
    qty_day: null,
    remaining_qty: null,
    spent_day: "54.00",
    actual_unit_mhr_cum: null,
    actual_unit_mhr_day: null,
  },
  {
    node_id: "s:kablo-grp",
    level: 2,
    name: "Kuvvetli akım",
    uom: null,
    contractor_type: "own",
    is_direct: null,
    pf_day: "1.1481",
    pf_day_band: "high",
    pf_cum: null,
    pf_cum_band: null,
    planned_qty: null,
    planned_unit_mhr: null,
    progress_pct_cum: "0.626389",
    qty_cum: null,
    qty_day: null,
    remaining_qty: null,
    spent_day: "54.00",
    actual_unit_mhr_cum: null,
    actual_unit_mhr_day: null,
  },
  {
    node_id: "i:kablo",
    level: 3,
    name: "Kablo çekimi",
    uom: "m",
    contractor_type: "own",
    is_direct: true,
    pf_day: "1.0741",
    pf_day_band: "high",
    pf_cum: "1.0198",
    pf_cum_band: "green",
    planned_qty: "18000.00",
    planned_unit_mhr: "0.2000",
    progress_pct_cum: "0.544444",
    qty_cum: "9800.00",
    qty_day: "145.00",
    remaining_qty: "8200.00",
    spent_day: "27.00",
    actual_unit_mhr_cum: "0.1961",
    actual_unit_mhr_day: "0.1862",
  },
  {
    node_id: "i:buat-priz",
    level: 3,
    name: "Buat/priz montajı",
    uom: "adet",
    contractor_type: "own",
    is_direct: true,
    pf_day: "1.2222",
    pf_day_band: "high",
    pf_cum: "0.9700",
    pf_cum_band: "amber",
    planned_qty: "2400.00",
    planned_unit_mhr: "1.5000",
    progress_pct_cum: "0.708333",
    qty_cum: "1700.00",
    qty_day: "22.00",
    remaining_qty: "700.00",
    spent_day: "27.00",
    actual_unit_mhr_cum: "1.5465",
    actual_unit_mhr_day: "1.2273",
  },
];

const TREND: EvDailyReport["trend"] = [
  {
    day: "2026-09-18",
    planned_pct_cum: "0.454042",
    progress_pct_cum: "0.426003",
    delta: "-0.028039",
    is_holiday: false,
    is_draft: false,
    is_future: false,
    earned_day: "318.00",
    spent_day: "318.00",
    pf_day: null,
    pf_rolling: null,
  },
  {
    day: "2026-09-19",
    planned_pct_cum: "0.460214",
    progress_pct_cum: "0.431969",
    delta: "-0.028245",
    is_holiday: false,
    is_draft: false,
    is_future: false,
    earned_day: "290.00",
    spent_day: "290.00",
    pf_day: null,
    pf_rolling: null,
  },
  {
    day: "2026-09-20",
    planned_pct_cum: "0.460214",
    progress_pct_cum: "0.431969",
    delta: "-0.028245",
    is_holiday: true,
    is_draft: false,
    is_future: false,
    earned_day: null,
    spent_day: null,
    pf_day: null,
    pf_rolling: null,
  },
  {
    day: "2026-09-21",
    planned_pct_cum: "0.466386",
    progress_pct_cum: "0.438860",
    delta: "-0.027525",
    is_holiday: false,
    is_draft: true,
    is_future: false,
    earned_day: "335.00",
    spent_day: "335.00",
    pf_day: null,
    pf_rolling: null,
  },
  {
    day: "2026-09-22",
    planned_pct_cum: "0.472557",
    progress_pct_cum: "0.445484",
    delta: "-0.027073",
    is_holiday: false,
    is_draft: false,
    is_future: false,
    earned_day: "322.00",
    spent_day: "322.00",
    pf_day: null,
    pf_rolling: null,
  },
  {
    day: "2026-09-23",
    planned_pct_cum: "0.478729",
    progress_pct_cum: "0.452232",
    delta: "-0.026497",
    is_holiday: false,
    is_draft: true,
    is_future: false,
    earned_day: "328.00",
    spent_day: "328.00",
    pf_day: null,
    pf_rolling: null,
  },
  {
    day: "2026-09-24",
    planned_pct_cum: "0.484900",
    progress_pct_cum: "0.458856",
    delta: "-0.026044",
    is_holiday: false,
    is_draft: false,
    is_future: false,
    earned_day: "322.00",
    spent_day: "322.00",
    pf_day: null,
    pf_rolling: null,
  },
];

const UNRATED_ENTRIES: EvWarning[] = [
  {
    code: "unrated_entry",
    target: "leaf",
    target_id: "i:buat-priz",
    message: "Buat/priz montajı için oran tanımlı değil",
    item_name: "Buat/priz montajı",
    // CEO ölçümü (7. tur, madde G3) — mockup dc.html:277 "Buat/priz · Çatı"
    // BÖLÜM adıdır (`section_name`), kalemin yapısal disiplini (Elektrik)
    // DEĞİL — ikisi ayrı alan, "Çatı" hiçbir L1 disiplinle örtüşmüyor.
    section_name: "Çatı",
    uom: "adet",
    value: "6",
  },
];

const PF_OUT_OF_BAND: EvWarning[] = [
  {
    code: "pf_out_of_band",
    target: "leaf",
    target_id: "i:ic-siva",
    message: "İç sıva bant dışı",
    item_name: "İç sıva",
    section_name: "Duvar & Sıva",
    value: "0.9375",
  },
  {
    code: "pf_out_of_band",
    target: "leaf",
    target_id: "i:tugla-duvar",
    message: "Tuğla duvar bant dışı",
    item_name: "Tuğla duvar",
    section_name: "Duvar & Sıva",
    value: "0.8938",
  },
  {
    code: "pf_out_of_band",
    target: "leaf",
    target_id: "i:temiz-su",
    message: "Temiz su borusu bant dışı",
    item_name: "Temiz su borusu",
    section_name: "Mekanik Tesisat",
    value: "0.9375",
  },
  {
    code: "pf_out_of_band",
    target: "leaf",
    target_id: "i:demir",
    message: "Demir bant dışı",
    item_name: "Demir",
    section_name: "Kaba İnşaat",
    value: "0.9913",
  },
];
const BASE: Omit<EvDailyReport, "status" | "approved_at" | "approved_by" | "version" | "draft_diary_dates" | "missing_diary_dates" | "report_date" | "day_no" | "report_no" | "generated_at"> = {
  calendar_start: "2026-05-06",
  calendar_end: "2027-03-30",
  footer: {
    spent_total_day: "310",
    timesheet_total_day: "326",
    undistributed_day: "16",
    unallocated_day: "0",
    undistributed_reason: "yardımcılar genel temizlikte",
  },
  kpis: KPIS,
  pf_bands: {
    daily: { red_below: "0.95", green_from: "0.95", high_above: "1.05" },
    cumulative: { red_below: "0.95", green_from: "1.00", high_above: null },
  },
  project_start: "2026-05-06",
  quantities: QUANTITIES,
  revision: { id: "rev-1", name: "Rev 1", number: 1, frozen_at: "2026-05-01T09:00:00+03:00" },
  tolerance_points: "2.0",
  trend: TREND,
  unrated_entries: UNRATED_ENTRIES,
  warnings: PF_OUT_OF_BAND,
  weather: WEATHER,
  week_end: "2026-09-24",
  week_no: 21,
  week_start: "2026-09-18",
};

/** Taslak — S10 bandı açık (`draft_diary_dates` dolu), onay PASİF. */
export const DAILY_REPORT_FIXTURE_DRAFT: EvDailyReport = {
  ...BASE,
  report_date: "2026-09-24",
  day_no: 142,
  report_no: 142,
  generated_at: "2026-09-24T18:40:00+03:00",
  status: "draft",
  approved_at: null,
  approved_by: null,
  version: null,
  draft_diary_dates: ["2026-09-21", "2026-09-23"],
  missing_diary_dates: [],
};

/**
 * Onaylı — S13 "· sürüm n", araç çubuğu salt okunur. `day_no`/`report_no`/
 * `generated_at` 22.09'a göre tutarlı (taslağın 24.09 kopyası DEĞİL).
 */
export const DAILY_REPORT_FIXTURE_APPROVED: EvDailyReport = {
  ...BASE,
  report_date: "2026-09-22",
  day_no: 140,
  report_no: 140,
  generated_at: "2026-09-22T18:40:00+03:00",
  status: "approved",
  approved_at: "2026-09-23T08:47:00+03:00",
  approved_by: { id: "u-mehmet", full_name: "Mehmet Kaya" },
  version: 1,
  draft_diary_dates: [],
  missing_diary_dates: [],
  // F3.6b lider denetimi (5. tur, arşiv özet kartı) — `BASE.kpis[0]` (Genel)
  // 24.09 (taslak günü) kümülatif değerlerini taşır; arşiv özet kartı
  // "Küm. planlı/gerçek/Sapma" BU raporun KENDİ günü (22.09) ile tutarlı
  // olmalı. `TREND` dizisindeki 22.09 satırıyla AYNI (Decimal, mockup
  // `P[4]`/`A[4]`): kart taslağın 24.09 toplamını göstermesin.
  kpis: BASE.kpis.map((row) =>
    row.kind === "overall"
      ? { ...row, planned_pct_cum: "0.472557", progress_pct_cum: "0.445484", variance: "-0.027073" }
      : row,
  ),
};

/** Üretilemedi — S11 "günlüğü yok" (o gün hiç günlük gönderilmedi). */
export const DAILY_REPORT_FIXTURE_NOT_GENERATED: EvDailyReport = {
  ...BASE,
  report_date: "2026-09-25",
  day_no: 143,
  report_no: null,
  generated_at: "2026-09-25T00:00:00+03:00",
  status: "not_generated",
  approved_at: null,
  approved_by: null,
  version: null,
  draft_diary_dates: [],
  missing_diary_dates: ["2026-09-25"],
  kpis: [],
  quantities: [],
  trend: [],
  footer: null,
  unrated_entries: [],
  warnings: [],
};
